### PR TITLE
fix: Instrument window bug

### LINKED ISSUE #11: Canvas: Random view panning when interacting with instrument toolbar
Occasionally, when clicking the instrument toolbar (such as toggling auto-refresh or manually refreshing) the view will teleport to to another location on the canvas or zoom in/out when unintended.

### PR DESCRIPTION
**Pull request by nakajimayoshi**
closes #11 

Previously when interacting with the instrument frame the TransformWrapper would randomly jump to to a different locations on the Canvas. This introduces a shared state between the Canvas & Instrument components such that the transform wrapper is disabled when the mouse is within an instrument frame.

### CODE REVIEW

File: src/pages/Workspace.tsx [hunk 1]
```diff
@@ -83,11 +83,11 @@ const CanvasLayer: React.FC = () => {
     const project = useWorkspaceSelector((state: WorkspaceState) => state.project.active);
     const dispatch = useWorkspaceDispatch();
 
-    const dndContext = useDndContext();
+    const [transformDisabled, setTransformDisabled] = useState(false);
 
     return (
         <TransformWrapper
-            disabled={dndContext.active !== null}
+            disabled={transformDisabled}
```
Comment (MikeRomaa) [inline src/pages/Workspace.tsx:90]: I'm pretty sure this was for preventing transforms while moving instruments around. I know that the `mouseEnter` technically also prevents this, but I would leave it in here and just `||` the two. Reason being is in the future `dndContext` will also be used for more functionality.

**Review by MikeRomaa — CHANGES_REQUESTED** [review]

**Review by MikeRomaa — APPROVED** [review]
